// Source of truth for the public legal surfaces (`/privacy-policy`, `/terms`).
// The route layer reads from this module instead of inlining 1000-line strings
// in `src/app/(public)/**`.
//
// TODO(legal): the copy below is draft placeholder content authored for the
// scaffold task `P15-PUBLIC-003`. It establishes the document anatomy, headings,
// and route wiring. The actual policy text must be reviewed (and replaced where
// needed) by the human before any production release. Do not ship the literal
// strings below as the canonical Mentor IB privacy policy or terms.

export type LegalDocumentSection = {
  body: readonly string[];
  heading: string;
  id: string;
  items?: readonly string[];
};

export type LegalDocumentContent = {
  effectiveDate: string;
  intro: string;
  sections: readonly LegalDocumentSection[];
  summary: readonly string[];
};

export const privacyPolicyContent: LegalDocumentContent = {
  effectiveDate: "2026-05-01",
  intro:
    "This privacy policy explains what Mentor IB collects when students, parents, and tutors use the product, how that information is used to run matching, bookings, lessons, payments, and support, and the choices each person has over their own data.",
  summary: [
    "Mentor IB collects only the account, fit, scheduling, and payment data needed to run IB tutor matching and lessons.",
    "We do not sell personal data, and we do not use lesson content for advertising.",
    "Students, parents, and tutors can ask to access, correct, or delete their account data through the support path.",
  ],
  sections: [
    {
      id: "scope",
      heading: "1. Scope of this policy",
      body: [
        "Mentor IB is a tutor-matching product operated by the Mentor IB team. This policy covers data collected through the Mentor IB website, the matching flow, tutor profiles, lesson booking, lesson delivery surfaces, messages, notifications, and account settings.",
        "Authenticated users also see a per-account privacy snapshot at /privacy that lists the legal notices they have already reviewed. That route does not replace this canonical public policy; it complements it.",
      ],
    },
    {
      id: "what-we-collect",
      heading: "2. Information we collect",
      body: [
        "Mentor IB collects information you provide directly, information generated by your use of the product, and a small number of operational signals required to keep the service reliable and safe.",
      ],
      items: [
        "Account information: email address, name, role (student, parent, or tutor), and time zone.",
        "Profile and matching information: subject focus, IB pressure points, schedule preferences, language preferences, and, for tutors, the published profile content used in tutor pages.",
        "Booking and lesson information: requested and confirmed lesson times, lesson notes you provide, and any reschedule or cancellation actions you take.",
        "Payment information: Stripe payment-method identifiers and authorization or capture records. Mentor IB does not store full card numbers on its own servers.",
        "Communications: messages exchanged inside the product, support requests, and feedback you send to us.",
        "Operational signals: sign-in events, security events, and limited analytics needed to operate, secure, and improve the product.",
      ],
    },
    {
      id: "how-we-use",
      heading: "3. How we use information",
      body: [
        "Mentor IB uses the data described above to run matching, to display tutor and lesson context, to schedule and bill lessons, to send transactional notifications, to operate trust and safety reviews, and to keep the product working as expected.",
        "We do not use the contents of your messages or lessons for advertising, and we do not sell personal data to third parties.",
      ],
    },
    {
      id: "legal-bases",
      heading: "4. Legal bases for processing",
      body: [
        "Where applicable law (such as the EU and UK GDPR) requires a stated legal basis, Mentor IB relies on contract performance for account and lesson features, legitimate interests for trust and safety and product improvement, consent for optional communications, and legal obligation where retention or disclosure is required by law.",
      ],
    },
    {
      id: "sharing",
      heading: "5. How information is shared",
      body: [
        "Mentor IB shares data only with the service providers needed to operate the product, and only to the extent each provider needs to perform its function.",
      ],
      items: [
        "Stripe for payment authorization, capture, and tutor payouts via Stripe Connect.",
        "Supabase for authentication, application database, file storage, and realtime delivery.",
        "Resend for transactional email delivery.",
        "PostHog for product analytics, configured to limit collection of sensitive personal data.",
        "Vercel for hosting and request delivery.",
        "Legal or regulatory recipients when disclosure is required by valid legal process or to protect the safety of users.",
      ],
    },
    {
      id: "retention",
      heading: "6. How long information is kept",
      body: [
        "Account, lesson, and payment records are retained for as long as the account is active and for the additional period needed to meet legal, accounting, and dispute-resolution obligations. Operational logs are retained for shorter windows aligned with security and reliability needs.",
        "Detailed retention windows are tracked in the Mentor IB data-retention policy and are reviewed regularly.",
      ],
    },
    {
      id: "rights",
      heading: "7. Your choices and rights",
      body: [
        "Depending on where you live, you may have the right to request access to your personal data, ask for corrections, request deletion, restrict or object to certain processing, or receive a portable copy of your data.",
        "You can begin any of these requests through Mentor IB support. We will verify the request, respond within the period required by applicable law, and explain any limitations that apply (for example, records we must retain for tax or dispute reasons).",
      ],
    },
    {
      id: "security",
      heading: "8. Security",
      body: [
        "Mentor IB uses industry-standard transport encryption, authentication, access control, and provider-side protections to safeguard data. No online service can be guaranteed completely secure, so we encourage you to use a strong account email provider and to report any suspected account compromise to support.",
      ],
    },
    {
      id: "children",
      heading: "9. Use by minors",
      body: [
        "Mentor IB is intended for IB students, who are often under 18. Where a student is below the age of digital consent in their jurisdiction, a parent or guardian is expected to set up and oversee the account. Mentor IB does not knowingly collect information from children outside of the IB tutoring context.",
      ],
    },
    {
      id: "international",
      heading: "10. International transfers",
      body: [
        "Mentor IB and its service providers may process data in countries other than the user's country of residence. Where required, transfers use appropriate safeguards such as standard contractual clauses or equivalent mechanisms recognised by applicable law.",
      ],
    },
    {
      id: "changes",
      heading: "11. Changes to this policy",
      body: [
        "When we update this policy, we revise the effective date above and, when changes are material, surface a legal notice inside the product so signed-in users can review the update before continuing.",
      ],
    },
    {
      id: "contact",
      heading: "12. How to contact us",
      body: [
        "Questions about this policy can be raised through Mentor IB support. Requests that require identity verification (for example, deletion or export) will be handled through the support workflow so we can confirm the request comes from the account holder.",
      ],
    },
  ],
};

export const termsContent: LegalDocumentContent = {
  effectiveDate: "2026-05-01",
  intro:
    "These terms set out the agreement between you and Mentor IB when you use the Mentor IB website, matching flow, tutor profiles, lesson booking, lesson delivery surfaces, and related features. By using Mentor IB you agree to these terms.",
  summary: [
    "Mentor IB is a tutor-matching service for IB students, parents, and tutors. It is not the IB Organization.",
    "Tutors are independent contractors. Mentor IB facilitates matching, scheduling, and payment but does not employ tutors.",
    "Bookings authorize a payment when requested and capture it when the tutor accepts. Cancellation, refund, and rescheduling rules follow the booking policy shown during checkout.",
  ],
  sections: [
    {
      id: "service",
      heading: "1. The Mentor IB service",
      body: [
        "Mentor IB connects IB students and parents with IB tutors. The product helps a user describe a learning need, surfaces suitable tutors, supports lesson booking and rescheduling, runs payment authorization and capture through Stripe, and provides messages, lesson context, and notifications.",
        "Mentor IB is an independent service. It is not affiliated with, endorsed by, or sponsored by the International Baccalaureate Organization.",
      ],
    },
    {
      id: "eligibility",
      heading: "2. Eligibility and accounts",
      body: [
        "To use Mentor IB you must be able to enter a binding agreement under the law of your jurisdiction. Students below the age of majority must use Mentor IB with the involvement of a parent or guardian.",
        "You are responsible for the accuracy of the information you provide, for keeping your sign-in details safe, and for activity that takes place on your account.",
      ],
    },
    {
      id: "tutors",
      heading: "3. Tutors are independent",
      body: [
        "Tutors who offer lessons through Mentor IB are independent professionals, not employees of Mentor IB. Mentor IB facilitates discovery, scheduling, payment, and a baseline trust-and-safety posture. It does not control the content of any individual lesson.",
        "Tutors are responsible for their own teaching, for the accuracy of profile claims, for compliance with applicable tax obligations, and for handling lessons professionally.",
      ],
    },
    {
      id: "booking",
      heading: "4. Booking, payment, and cancellation",
      body: [
        "When a student requests a lesson, Stripe places a payment authorization on the student's payment method. If the tutor accepts the request within the booking window, the authorization is captured. If the tutor declines or the request expires, the authorization is released without a charge.",
        "Reschedules, cancellations, refunds, and no-show handling follow the booking policy visible at the time of checkout. Specific tutor-level conditions, when present, are shown alongside the booking surface.",
        "Tutor earnings are routed through Stripe Connect Express. Tutors agree to Stripe's Connected Account terms in addition to these terms.",
      ],
    },
    {
      id: "acceptable-use",
      heading: "5. Acceptable use",
      body: [
        "When using Mentor IB you agree not to misuse the product or harm other users.",
      ],
      items: [
        "Do not impersonate another person, misrepresent IB qualifications, or post false trust signals.",
        "Do not use Mentor IB to solicit users to circumvent the booking and payment flow.",
        "Do not harass, threaten, or target any user, and do not use the product to share content that is illegal where it is being delivered.",
        "Do not interfere with the security of the product, attempt to extract data outside of intended access, or abuse messaging and notification channels.",
      ],
    },
    {
      id: "content",
      heading: "6. Content you provide",
      body: [
        "You retain ownership of the content you submit to Mentor IB (for example, profile descriptions, lesson notes, and messages). You grant Mentor IB a worldwide, royalty-free licence to host, display, and process that content to the extent needed to operate the service for you and the people you are interacting with.",
        "You are responsible for ensuring that the content you submit does not infringe the rights of others and does not violate the acceptable-use rules above.",
      ],
    },
    {
      id: "intellectual-property",
      heading: "7. Mentor IB intellectual property",
      body: [
        "The Mentor IB name, brand, product design, software, and unique content are owned by Mentor IB. These terms do not grant you any right to reuse Mentor IB branding outside of normal product use.",
      ],
    },
    {
      id: "termination",
      heading: "8. Suspension and termination",
      body: [
        "Mentor IB may suspend or close an account when these terms or the acceptable-use rules are violated, when payment obligations are not met, when trust-and-safety review requires it, or when the law requires it.",
        "You can stop using Mentor IB at any time. Where you have outstanding bookings, payments, or lessons in progress, those may need to be resolved before account closure can complete.",
      ],
    },
    {
      id: "disclaimers",
      heading: "9. Disclaimers",
      body: [
        "Mentor IB is provided on an as-is basis. To the extent permitted by law, Mentor IB disclaims implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Mentor IB does not guarantee that a specific tutor match will produce a specific academic result.",
      ],
    },
    {
      id: "liability",
      heading: "10. Limitation of liability",
      body: [
        "To the extent permitted by law, Mentor IB will not be liable for indirect, incidental, special, consequential, or punitive damages arising out of or in connection with use of the product. Direct liability for any claim related to the service is limited to the amount you paid to Mentor IB in the twelve months before the event giving rise to the claim.",
      ],
    },
    {
      id: "law",
      heading: "11. Governing law and disputes",
      body: [
        "These terms are governed by the laws of the jurisdiction stated in the final published version of this document. Disputes that cannot be resolved through Mentor IB support will be handled in the courts of that jurisdiction, except where applicable consumer-protection law gives you a different right.",
      ],
    },
    {
      id: "changes",
      heading: "12. Changes to these terms",
      body: [
        "When we update these terms, we revise the effective date above and, when changes are material, surface a legal notice inside the product so signed-in users can review the update before continuing to use the service.",
      ],
    },
    {
      id: "contact",
      heading: "13. How to contact us",
      body: [
        "Questions about these terms can be raised through Mentor IB support.",
      ],
    },
  ],
};
